### PR TITLE
Create app

### PR DESCRIPTION
**Pull request by posadvladimir**

### CODE REVIEW

**Comment by elen-s17** [comment]
I cannot review the app, because I could not open it on the browser to check how it actually works.

**Comment by posadvladimir** [comment]
> I cannot review the app, because I could not open it on the browser to check how it actually works.

The startup process is described in the README.md.

1. Go to the folder with the project and run **npm install**  in the console.
2. Then after the installation is complete, run **npm start**. The application will start at http://localhost:3000/

**Comment by amchos** [comment]
Cool! You found funny API. 
Good attention to little details (such a favicon image for browser tab) )
Nice design) 
I still do not know about some stuff that was used there (( but I can say that code style is good and it was an interesting to me to review that project

Success.

**Comment by artyomnajaryan01** [comment]
It works. CSS is good. (Success)

**Pull request merged**
